wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    huggingface_version: 3.4.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
learning_rate:
  desc: null
  value: 0.00016478246420334415
num_train_epochs:
  desc: null
  value: 19
train_batch_size:
  desc: null
  value: 98
